"""delete runner and volunteer info tables

Revision ID: 066e5a410888
Revises: 25f6d730fa48
Create Date: 2019-11-27 10:34:27.516044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066e5a410888'
down_revision = '25f6d730fa48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runner_info')
    op.drop_table('volunteer_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('restream', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('commentary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('tracking', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('organizer', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='participant_id'),
    sa.PrimaryKeyConstraint('id', name='volunteers_pkey')
    )
    op.create_table('runner_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('srl_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('twitch_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('src_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('availability_weekday', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('availability_weekend', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('input_method', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='participant_id'),
    sa.PrimaryKeyConstraint('id', name='runners_pkey')
    )
    # ### end Alembic commands ###
