"""initial models

Revision ID: 09d60a3fb2b1
Revises: 
Create Date: 2019-11-07 15:37:06.277214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d60a3fb2b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'question_responses',
        existing_comment='responses to the questions in the questions table',
        schema=None
    )
    op.drop_table_comment(
        'runner_info',
        existing_comment='Runner-specific information',
        schema=None
    )
    op.drop_table_comment(
        'users',
        existing_comment='Information that is provided by all participants',
        schema=None
    )
    op.drop_table_comment(
        'volunteer_info',
        existing_comment='Volunteer-specific information',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'volunteer_info',
        'Volunteer-specific information',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'users',
        'Information that is provided by all participants',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'runner_info',
        'Runner-specific information',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'question_responses',
        'responses to the questions in the questions table',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###
