"""active column for tournaments added back

Revision ID: 1ebac9496acd
Revises: fef1c6f24426
Create Date: 2019-11-15 10:55:22.231087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebac9496acd'
down_revision = 'fef1c6f24426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runner_info', 'availability_weekday',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('runner_info', 'availability_weekend',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('tournaments', sa.Column('active', sa.Boolean(), nullable=True))
    op.alter_column('tournaments', 'visible',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'visible',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('tournaments', 'active')
    op.alter_column('runner_info', 'availability_weekend',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('runner_info', 'availability_weekday',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
