"""moved organizer up a level to the User object so organizers aren't necessarily volunteers. Defaulted new tournaments to inactive and new users to not organizers.

Revision ID: 256b01715de8
Revises: 1ebac9496acd
Create Date: 2019-11-15 11:05:56.061075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256b01715de8'
down_revision = '1ebac9496acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organizer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'organizer')
    # ### end Alembic commands ###
