"""still trying to reorder columns

Revision ID: 25f6d730fa48
Revises: 3ff2cbb4b1bd
Create Date: 2019-11-27 10:19:02.688194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f6d730fa48'
down_revision = '3ff2cbb4b1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('commentary', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('restream', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('tracking', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tracking')
    op.drop_column('users', 'restream')
    op.drop_column('users', 'commentary')
    # ### end Alembic commands ###
