"""moved runner and volunteer info into users table. it should have been there to begin with.

Revision ID: 3c40490eadd2
Revises: 8848329cd7cd
Create Date: 2019-11-27 09:39:49.206347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c40490eadd2'
down_revision = '8848329cd7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('availability_weekday', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('availability_weekend', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('commentary', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('input_method', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('restream', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('src_name', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('srl_name', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('tracking', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('twitch_name', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitch_name')
    op.drop_column('users', 'tracking')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'srl_name')
    op.drop_column('users', 'src_name')
    op.drop_column('users', 'restream')
    op.drop_column('users', 'input_method')
    op.drop_column('users', 'commentary')
    op.drop_column('users', 'availability_weekend')
    op.drop_column('users', 'availability_weekday')
    # ### end Alembic commands ###
