"""trying to reorder columns

Revision ID: 3ff2cbb4b1bd
Revises: 3c40490eadd2
Create Date: 2019-11-27 10:18:25.393607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff2cbb4b1bd'
down_revision = '3c40490eadd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tracking')
    op.drop_column('users', 'commentary')
    op.drop_column('users', 'restream')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('restream', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('commentary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('tracking', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
