"""empty message

Revision ID: 795b45dc3025
Revises: 09d60a3fb2b1
Create Date: 2019-11-07 16:22:13.489976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795b45dc3025'
down_revision = '09d60a3fb2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('races', 'tournament_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('races', 'tournament_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
