"""empty message

Revision ID: eaaf061e4c3c
Revises: 480eec781a4e
Create Date: 2019-12-22 19:01:48.592337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaaf061e4c3c'
down_revision = '480eec781a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'group_member',
        existing_comment='association between tournament and user for group members',
        schema=None
    )
    op.drop_table_comment(
        'race_result',
        existing_comment="Association table between races and users, each record holds a single user's time for one race",
        schema=None
    )
    op.drop_table_comment(
        'runner_seed',
        existing_comment='currently unused',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'runner_seed',
        'currently unused',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'race_result',
        "Association table between races and users, each record holds a single user's time for one race",
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'group_member',
        'association between tournament and user for group members',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###
