"""password hash and salt

Revision ID: fb975b9c2dbd
Revises: 795b45dc3025
Create Date: 2019-11-11 15:46:45.193807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb975b9c2dbd'
down_revision = '795b45dc3025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_id', 'runner_info', type_='foreignkey')
    op.drop_column('runner_info', 'group_id')
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('salt', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt')
    op.drop_column('users', 'password_hash')
    op.add_column('runner_info', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('group_id', 'runner_info', 'group_names', ['group_id'], ['id'])
    # ### end Alembic commands ###
